name: taskati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.2
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  gap: ^3.0.1
  
     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/
      - assets/fonts/
      - assets/lotti/
  fonts:
      - family: Lexend 
        fonts:
          - asset: assets/fonts/LexendDeca-Regular.ttf
          - weight: 400
          - asset: assets/fonts/LexendDeca-Medium.ttf
          - weight: 500
          - asset: assets/fonts/LexendDeca-SemiBold.ttf
          - weight: 600
          - asset: assets/fonts/LexendDeca-Bold.ttf
          - weight: 700

